source("setup.R")

png("plot4.png")
par(mfrow=c(2,2))
plot(y=as.numeric(dff$Global_active_power), x=strptime( dff$DateTime, "%d/%m/%Y %H:%M:%S"), type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dff$DateTime = paste(dff$Date , dff$Time)
plot(y=as.numeric(dff$Voltage), x=strptime( dff$DateTime, "%d/%m/%Y %H:%M:%S"), type = "l", xlab = "datetime", ylab = "Voltage")
plot(y=dff$Sub_metering_1, x=strptime( dff$DateTime, "%d/%m/%Y %H:%M:%S"), type="l", xlab = "", ylab="Energy SM" )
lines(dff$Sub_metering_2, x=strptime( dff$DateTime, "%d/%m/%Y %H:%M:%S"), col="red")
lines(dff$Sub_metering_3, x=strptime( dff$DateTime, "%d/%m/%Y %H:%M:%S"), col="blue")
legend("topright", lty=c(1,1,1), legend=c("Submetering1", "Submetering2", "Submetering3"), col=c("black","red", "blue"))
plot(y=as.numeric(dff$Global_reactive_power), x=strptime( dff$DateTime, "%d/%m/%Y %H:%M:%S"), type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()